apiVersion: v1
kind: Service
metadata:
  name: database
spec:
  ports:
    - name: "5432"
      port: 5432
      targetPort: 5432
  selector:
    app: database

---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  selector:
    app: rabbitmq
  ports:
    - name: "5672"
      port: 5672
      targetPort: 5672
    - name: "15672"
      port: 15672
      targetPort: 15672

---
apiVersion: v1
kind: Service
metadata:
  name: session-service
spec:
  ports:
    - name: "8081"
      port: 8081
      targetPort: 8081
  selector:
    app: session-service

---
apiVersion: v1
kind: Service
metadata:
  name: hotel-service
spec:
  ports:
    - name: "8082"
      port: 8082
      targetPort: 8082
  selector:
    app: hotel-service

---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
spec:
  ports:
    - name: "8084"
      port: 8084
      targetPort: 8084
  selector:
    app: payment-service

---
apiVersion: v1
kind: Service
metadata:
  name: loyalty-service
spec:
  ports:
    - name: "8085"
      port: 8085
      targetPort: 8085
  selector:
    app: loyalty-service

---
apiVersion: v1
kind: Service
metadata:
  name: report-service
spec:
  ports:
    - name: "8086"
      port: 8086
      targetPort: 8086
  selector:
    app: report-service

---
apiVersion: v1
kind: Service
metadata:
  name: booking-service
spec:
  ports:
    - name: "8083"
      port: 8083
      targetPort: 8083
  selector:
    app: booking-service

---
apiVersion: v1
kind: Service
metadata:
  name: gateway-service
spec:
  ports:
    - name: "8087"
      port: 8087
      targetPort: 8087
  selector:
    app: gateway-service
