# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "bento/ubuntu-22.04"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
    vb.cpus = 1
  end

  config.vm.define "manager" do |man|
    man.vm.hostname = "manager"
    man.vm.network "private_network", ip: "192.168.56.10"
    man.vm.network "forwarded_port", guest: 8081, host: 8081
    man.vm.network "forwarded_port", guest: 8087, host: 8087
    # man.vm.provision "shell", inline: <<-SHELL
    #   sudo chown -R vagrant:vagrant /home/vagrant/
    # SHELL
  end

  config.vm.define "node01" do |n1|
    n1.vm.hostname = "node01"
    n1.vm.network "private_network", ip: "192.168.56.11"
  end

  config.vm.define "node02" do |n2|
    n2.vm.hostname = "node02"
    n2.vm.network "private_network", ip: "192.168.56.12"
  end

end
