Vagrant.configure("2") do |config|

  config.vm.box = "bento/ubuntu-22.04"
  config.vm.network "private_network", type: "dhcp"

  # config.vm.synced_folder "./services", "/home/vagrant/src/services"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
    vb.cpus = 1
  end


  config.vm.define "manager" do |man|
    man.vm.hostname = "manager"
    man.vm.provision "shell", inline: <<-SHELL
      mkdir -p /home/vagrant/src
      sudo chown -R vagrant:vagrant /home/vagrant/src
    SHELL
  end

  config.vm.define "node01" do |n1|
    n1.vm.hostname = "node01"
    n1.vm.network "forwarded_port", guest: 80, host: 8080
  end

  config.vm.define "node02" do |n2|
    n2.vm.hostname = "node02"
  end

  config.vm.provision "shell", inline: <<-SHELL
    echo $(hostname -I | awk '{print $2}') >> /vagrant/ip.txt
  SHELL
end
