# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "bento/ubuntu-22.04"
  config.vm.network "private_network", type: "dhcp"

  config.vm.synced_folder "./services", "/home/vagrant/src/services"
  config.vm.synced_folder "./scripts", "/home/vagrant/src/scripts"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
    vb.cpus = 1
  end

  config.vm.provision "shell", path: "scripts/install_docker.sh"

  config.vm.define "manager01" do |man|
    man.vm.hostname = "manager01"
    man.vm.provision "shell", path: "scripts/init_swarm.sh"
    man.vm.provision "shell", inline: <<-SHELL
      sudo chown -R vagrant:vagrant /home/vagrant/src
    SHELL
  end

  config.vm.define "worker01" do |w1|
    w1.vm.hostname = "worker01"
    w1.vm.provision "shell", path: "scripts/join_swarm.sh"
  end

  config.vm.define "worker02" do |w2|
    w2.vm.hostname = "worker02"
    w2.vm.provision "shell", path: "scripts/join_swarm.sh"
  end

  # config.vm.provision "shell", inline: <<-SHELL
  # scripts/install_docker.sh
  # SHELL
end
