apiVersion: apps/v1
kind: Deployment
metadata:
  name: booking-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: booking-service
  template:
    metadata:
      labels:
        app: booking-service
    spec:
      containers:
        - image: pimmarde07/booking-service:latest
          name: booking-service
          ports:
            - containerPort: 8083
              protocol: TCP
          env:
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: configmap
                  key: DATABASE_HOST
            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  name: configmap
                  key: DATABASE_PORT
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: configmap
                  key: DATABASE_BOOKING
            - name: RABBIT_MQ_HOST
              valueFrom:
                configMapKeyRef:
                  name: configmap
                  key: RABBITMQ_HOST
            - name: RABBIT_MQ_PORT
              valueFrom:
                configMapKeyRef:
                  name: configmap
                  key: RABBITMQ_PORT
            - name: RABBIT_MQ_USER
              valueFrom:
                configMapKeyRef:
                  name: configmap
                  key: RABBIT_MQ_USER
            - name: RABBIT_MQ_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: configmap
                  key: RABBIT_MQ_PASSWORD
            - name: RABBIT_MQ_QUEUE_NAME
              valueFrom:
                configMapKeyRef:
                  name: configmap
                  key: RABBIT_MQ_QUEUE_NAME
            - name: RABBIT_MQ_EXCHANGE
              valueFrom:
                configMapKeyRef:
                  name: configmap
                  key: RABBIT_MQ_EXCHANGE
            - name: HOTEL_SERVICE_HOST
              valueFrom:
                configMapKeyRef:
                  name: configmap
                  key: HOTEL_SERVICE_HOST
            - name: HOTEL_SERVICE_PORT
              valueFrom:
                configMapKeyRef:
                  name: configmap
                  key: HOTEL_SERVICE_PORT
            - name: PAYMENT_SERVICE_HOST
              valueFrom:
                configMapKeyRef:
                  name: configmap
                  key: PAYMENT_SERVICE_HOST
            - name: PAYMENT_SERVICE_PORT
              valueFrom:
                configMapKeyRef:
                  name: configmap
                  key: PAYMENT_SERVICE_PORT
            - name: LOYALTY_SERVICE_HOST
              valueFrom:
                configMapKeyRef:
                  name: configmap
                  key: LOYALTY_SERVICE_HOST
            - name: LOYALTY_SERVICE_PORT
              valueFrom:
                configMapKeyRef:
                  name: configmap
                  key: LOYALTY_SERVICE_PORT
