---
# - name: Copy Consul client config
#   copy:
#     src: consul_client.hcl
#     dest: /etc/consul.d/consul_client.hcl
#     owner: root
#     group: root
#     mode: '0644'

- name: Reload systemd to apply changes
  systemd:
    daemon_reload: yes

- name: Ensure Consul service is started and enabled
  systemd:
    name: consul
    state: started
    enabled: yes
