---
- name: Ensure apt cache is updated
  apt:
    update_cache: yes

- name: Install required packages
  apt:
    name:
      - apt-transport-https
      - gnupg2
      - curl
      - lsb-release
    state: present

- name: Add Envoy GPG key
  shell: |
    curl -sL 'https://deb.dl.getenvoy.io/public/gpg.8115BA8E629CC074.key' | sudo gpg --dearmor -o /usr/share/keyrings/getenvoy-keyring.gpg
  # args:
  #   creates: /usr/share/keyrings/getenvoy-keyring.gpg

- name: Verify Envoy GPG key
  shell: |
    echo a077cb587a1b622e03aa4bf2f3689de14658a9497a9af2c427bba5f4cc3c4723 /usr/share/keyrings/getenvoy-keyring.gpg | sha256sum --check
  register: gpg_key_check
  failed_when: gpg_key_check.rc != 0

- name: Add Envoy APT repository
  shell: |
    echo "deb [arch=amd64 signed-by=/usr/share/keyrings/getenvoy-keyring.gpg] https://deb.dl.getenvoy.io/public/deb/ubuntu $(lsb_release -cs) main" | tee /etc/apt/sources.list.d/getenvoy.list
  args:
    creates: /etc/apt/sources.list.d/getenvoy.list

- name: Update apt cache again
  apt:
    update_cache: yes

- name: Install Envoy
  apt:
    name: getenvoy-envoy
    state: present
