global:
  resolve_timeout: 5m
  smtp_smarthost: 'smtp.mail.ru:587'
  smtp_from: '<тут почта откуда>'
  smtp_auth_username: '<тут почта откуда>'
  smtp_auth_password: '<пароль для авторизации>'

route:
  receiver: 'all-alerts'
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 5m
  repeat_interval: 1h
  routes:
    - receiver: 'all-alerts'
      match:
        severity: critical

receivers:
  - name: 'all-alerts'
    email_configs:
      - to: '<почта куда будут приходить письма>'
        send_resolved: true
    telegram_configs:
      - chat_id: <id телеграма>
        send_resolved: true
        bot_token: 'тут токен бота'
