apiVersion: apps/v1
kind: Deployment
metadata:
  name: session-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: session-service
  template:
    metadata:
      labels:
        app: session-service
    spec:
      containers:
        - image: pimmarde07/session-service:latest
          name: session-service
          ports:
            - containerPort: 8081
              protocol: TCP
          env:
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: configmap
                  key: DATABASE_HOST
            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  name: configmap
                  key: DATABASE_PORT
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: configmap
                  key: DATABASE_SESSION
