---
- name: Create user for consul
  user:
    name: consul
    comment: User for consul
    system: true

- name: Ensure Consul config directory exists
  file:
    path: /etc/consul.d
    state: directory
    owner: consul
    group: consul
    mode: '0755'

- name: Copy Consul server config
  copy:
    src: ../consul01/consul_server.hcl
    dest: /etc/consul.d/consul_server.hcl
    owner: consul
    group: consul
    mode: '0644'

- name: Update apt cache
  apt:
    update_cache: yes

- name: Install Consul
  apt:
    name: consul
    state: present
