apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
        - env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: POSTGRES_PASSWORD
          image: pimmarde07/database:latest
          name: database
          ports:
            - containerPort: 5432
              protocol: TCP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - image: pimmarde07/rabbitmq:latest
          name: rabbitmq
          ports:
            - containerPort: 5672
              protocol: TCP
            - containerPort: 15672
              protocol: TCP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: session-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: session-service
  template:
    metadata:
      labels:
        app: session-service
    spec:
      containers:
        - image: pimmarde07/session-service:latest
          name: session-service
          ports:
            - containerPort: 8081
              protocol: TCP
          env:
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: configmap
                  key: DATABASE_HOST
            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  name: configmap
                  key: DATABASE_PORT
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: configmap
                  key: DATABASE_SESSION

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotel-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hotel-service
  template:
    metadata:
      labels:
        app: hotel-service
    spec:
      containers:
        - image: pimmarde07/hotel-service:latest
          name: hotel-service
          ports:
            - containerPort: 8082
              protocol: TCP
          env:
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: configmap
                  key: DATABASE_HOST
            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  name: configmap
                  key: DATABASE_PORT
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: configmap
                  key: DATABASE_HOTELS

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
        - image: pimmarde07/payment-service:latest
          name: payment-service
          ports:
            - containerPort: 8084
              protocol: TCP
          env:
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: configmap
                  key: DATABASE_HOST
            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  name: configmap
                  key: DATABASE_PORT
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: configmap
                  key: DATABASE_PAYMENT

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loyalty-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loyalty-service
  template:
    metadata:
      labels:
        app: loyalty-service
    spec:
      containers:
        - image: pimmarde07/loyalty-service:latest
          name: loyalty-service
          ports:
            - containerPort: 8085
              protocol: TCP
          env:
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: configmap
                  key: DATABASE_HOST
            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  name: configmap
                  key: DATABASE_PORT
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: configmap
                  key: DATABASE_LOYALTY

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: report-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: report-service
  template:
    metadata:
      labels:
        app: report-service
    spec:
      containers:
        - image: pimmarde07/report-service:latest
          name: report-service
          ports:
            - containerPort: 8086
              protocol: TCP
          env:
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: configmap
                  key: DATABASE_HOST
            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  name: configmap
                  key: DATABASE_PORT
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: configmap
                  key: DATABASE_REPORT
            - name: RABBIT_MQ_HOST
              valueFrom:
                configMapKeyRef:
                  name: configmap
                  key: RABBITMQ_HOST
            - name: RABBIT_MQ_PORT
              valueFrom:
                configMapKeyRef:
                  name: configmap
                  key: RABBITMQ_PORT
            - name: RABBIT_MQ_USER
              valueFrom:
                configMapKeyRef:
                  name: configmap
                  key: RABBIT_MQ_USER
            - name: RABBIT_MQ_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: configmap
                  key: RABBIT_MQ_PASSWORD
            - name: RABBIT_MQ_QUEUE_NAME
              valueFrom:
                configMapKeyRef:
                  name: configmap
                  key: RABBIT_MQ_QUEUE_NAME
            - name: RABBIT_MQ_EXCHANGE
              valueFrom:
                configMapKeyRef:
                  name: configmap
                  key: RABBIT_MQ_EXCHANGE

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: booking-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: booking-service
  template:
    metadata:
      labels:
        app: booking-service
    spec:
      containers:
        - image: pimmarde07/booking-service:latest
          name: booking-service
          ports:
            - containerPort: 8083
              protocol: TCP
          env:
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: configmap
                  key: DATABASE_HOST
            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  name: configmap
                  key: DATABASE_PORT
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: configmap
                  key: DATABASE_BOOKING
            - name: RABBIT_MQ_HOST
              valueFrom:
                configMapKeyRef:
                  name: configmap
                  key: RABBITMQ_HOST
            - name: RABBIT_MQ_PORT
              valueFrom:
                configMapKeyRef:
                  name: configmap
                  key: RABBITMQ_PORT
            - name: RABBIT_MQ_USER
              valueFrom:
                configMapKeyRef:
                  name: configmap
                  key: RABBIT_MQ_USER
            - name: RABBIT_MQ_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: configmap
                  key: RABBIT_MQ_PASSWORD
            - name: RABBIT_MQ_QUEUE_NAME
              valueFrom:
                configMapKeyRef:
                  name: configmap
                  key: RABBIT_MQ_QUEUE_NAME
            - name: RABBIT_MQ_EXCHANGE
              valueFrom:
                configMapKeyRef:
                  name: configmap
                  key: RABBIT_MQ_EXCHANGE
            - name: HOTEL_SERVICE_HOST
              valueFrom:
                configMapKeyRef:
                  name: configmap
                  key: HOTEL_SERVICE_HOST
            - name: HOTEL_SERVICE_PORT
              valueFrom:
                configMapKeyRef:
                  name: configmap
                  key: HOTEL_SERVICE_PORT
            - name: PAYMENT_SERVICE_HOST
              valueFrom:
                configMapKeyRef:
                  name: configmap
                  key: PAYMENT_SERVICE_HOST
            - name: PAYMENT_SERVICE_PORT
              valueFrom:
                configMapKeyRef:
                  name: configmap
                  key: PAYMENT_SERVICE_PORT
            - name: LOYALTY_SERVICE_HOST
              valueFrom:
                configMapKeyRef:
                  name: configmap
                  key: LOYALTY_SERVICE_HOST
            - name: LOYALTY_SERVICE_PORT
              valueFrom:
                configMapKeyRef:
                  name: configmap
                  key: LOYALTY_SERVICE_PORT

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-service
spec:
  replicas: {{ .Values.gatewayservice.replicaCount | default 1 }}
  # strategy:
  #   type: Recreate
  # strategy:
  #   type: RollingUpdate
  #   rollingUpdate:
  #     maxUnavailable: 1
  #     maxSurge: 1
  selector:
    matchLabels:
      app: gateway-service
  template:
    metadata:
      labels:
        app: gateway-service
    spec:
      containers:
        - image: pimmarde07/gateway-service:latest
          name: gateway-service
          ports:
            - containerPort: 8087
              protocol: TCP
          env:
            - name: SESSION_SERVICE_HOST
              valueFrom:
                configMapKeyRef:
                  name: configmap
                  key: SESSION_SERVICE_HOST
            - name: SESSION_SERVICE_PORT
              valueFrom:
                configMapKeyRef:
                  name: configmap
                  key: SESSION_SERVICE_PORT
            - name: HOTEL_SERVICE_HOST
              valueFrom:
                configMapKeyRef:
                  name: configmap
                  key: HOTEL_SERVICE_HOST
            - name: HOTEL_SERVICE_PORT
              valueFrom:
                configMapKeyRef:
                  name: configmap
                  key: HOTEL_SERVICE_PORT
            - name: BOOKING_SERVICE_HOST
              valueFrom:
                configMapKeyRef:
                  name: configmap
                  key: BOOKING_SERVICE_HOST
            - name: BOOKING_SERVICE_PORT
              valueFrom:
                configMapKeyRef:
                  name: configmap
                  key: BOOKING_SERVICE_PORT
            - name: PAYMENT_SERVICE_HOST
              valueFrom:
                configMapKeyRef:
                  name: configmap
                  key: PAYMENT_SERVICE_HOST
            - name: PAYMENT_SERVICE_PORT
              valueFrom:
                configMapKeyRef:
                  name: configmap
                  key: PAYMENT_SERVICE_PORT
            - name: LOYALTY_SERVICE_HOST
              valueFrom:
                configMapKeyRef:
                  name: configmap
                  key: LOYALTY_SERVICE_HOST
            - name: LOYALTY_SERVICE_PORT
              valueFrom:
                configMapKeyRef:
                  name: configmap
                  key: LOYALTY_SERVICE_PORT
            - name: REPORT_SERVICE_HOST
              valueFrom:
                configMapKeyRef:
                  name: configmap
                  key: REPORT_SERVICE_HOST
            - name: REPORT_SERVICE_PORT
              valueFrom:
                configMapKeyRef:
                  name: configmap
                  key: REPORT_SERVICE_PORT
